#需增加配置，当然外部项目可以覆盖此配置，只需要将此配置删除即可
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      filters: stat
      web-stat-filter:
        enabled: true
        exclusions: /druid/*
        stat-view-servlet:
          enabled: true
          login-username: admin
          login-password: admin
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true

jwt:
  name: token
  secret: manage
  expire: 86400
  keyPrefix: xgl_jyg_manage_
